[project]
name = "image-to-geolocation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-ai>=0.0.52",
    "pytest>=8.3.5",
    "python-dotenv>=1.1.0",
    "ruff>=0.11.4",
    "streamlit>=1.44.1",
]
